### ISSUE TITLE
Translation bugs when default language is not 'en'

### ISSUE THREAD

**Issue by mordoviu** [globaleaks/globaleaks-whistleblowing-software#4315] opened 2024-11-15 10:12 UTC
### What version of GlobaLeaks are you using?

5.0.26

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

In my Globaleaks installation, I am using two languages, German and English, and German is (and has to be) the default language. After Upgrade to Globaleaks 5 I am observing some bugs in the translation when I switch the language from German to English as admin or whistleblower: some menu items and questions are not translated to English, they stay in German. This bug however cannot be reproduced when English is set as default language. Please see screenshots attached for a visual example.
![translation_bug_example_globaleaks_5](https://github.com/user-attachments/assets/0851ef33-363e-47c3-8e3d-aa675666a241)

**Comment by mordoviu** [comment] 2024-11-25 09:34
Issue remains on 5.0.28

**Comment by evilaliv3** [comment] 2024-11-25 09:59
Thank you @mordoviu 

@msmannan00 : would you please check into this with priority?

**Comment by msmannan00** [comment] 2024-11-25 11:24
sure, will get back here shortly

**Comment by msmannan00** [comment] 2024-11-25 14:45
@evilaliv3 the issue is that en.json doesn't contain the keys, for instance Alternative contact method works because its present in en.json
adding "Specify" and "Would you like to tell us who you are" in en makes it work.

**Comment by evilaliv3** [comment] 2024-11-25 14:47
Ah, well noted thank you!

**Comment by mordoviu** [comment] 2024-11-27 15:46
Sure! I added a video demonstrating the behavior, the default language is set to 'de'.
[Screencast from 27.11.2024 16:42:50.webm](https://github.com/user-attachments/assets/71fcdf7d-129e-4bf0-9fb1-17fb3d3d165a)

Let me know, if you need more information.

**Comment by evilaliv3** [comment] 2024-11-30 11:37
Fix implemented, will be included in release 5.0.32

**Closed by evilaliv3** 2024-11-30 11:37 UTC
Labels: T: Bug, C: Client
